export type ColorPalette = {
    red : string,
    black : string,
    white : string,
    orange : string,
    blue : string,
    yellow : string,
    transparent : string,
    primaryColor: string,
    imgBgColor : string,
    bgColor  : string,
    tavIndicatorColor : string,
    tabActiveColor : string,
    tavInActiveColor : string,
    editTxtPrimaryCont : string,
    editTxtSecondaryCont : string,
    primaryTxtColor : string,
    secondaryTxtColor : string,
    editTxtColor : string,
    commonBtnColor : string,
    bottomNavActiveColor : string,
    bottomNavInActiveColor : string,
    skeletonContentColor : string,
    cardBgColor : string,
    cardPrimaryColor : string,
    iconBgColor : string,
    primaryIconColor : string,
    cardTitleTxtColor : string,
    cardDesTxtColor : string,
    viewLineColor : string,
    secondaryIconColor : string,
    fbIconColor : string,
    appleIconColor : string,
    googleIconColor : string,
}

type ColorPaletteContainer = {
    light: ColorPalette
    dark: ColorPalette
    [key: string]: ColorPalette
}

export const colorPaletteContainer: ColorPaletteContainer = {
    light : {
        black : "#000000",
        white : "#FFFFFF",
        red : "#EF4444",
        blue : "#1877F2",
        orange : "#F97316",
        yellow : "#FFE000",
        transparent : "rgba(0,0,0,0.7)",
        primaryColor: '#FFFFFF',
        bgColor : '#F0F0F0',
        imgBgColor : "#F0F0F0",
        tavIndicatorColor : "#1877F2",
        tabActiveColor : "#1877F2",
        tavInActiveColor : "#A1A4AA",
        editTxtPrimaryCont : "#FFFFFF",
        editTxtSecondaryCont : "#F0F0F0",
        editTxtColor : '#000000',
        commonBtnColor : '#1877F2',
        primaryTxtColor : '#000000',
        secondaryTxtColor : '#707070',
        cardTitleTxtColor : '#333',
        cardDesTxtColor : '#b9b9b9',
        bottomNavActiveColor : '#006697',
        bottomNavInActiveColor : '#BABABA',
        skeletonContentColor : 'rgba(128,128,128,0.17)',
        cardBgColor : '#FFFFFF',
        cardPrimaryColor : '#F0F0F0',
        iconBgColor : "#F0F0F0",
        primaryIconColor : '#000000',
        secondaryIconColor : "#F1F1F1",
        viewLineColor : "#d9bfbf",
        fbIconColor : "#4267B2",
        appleIconColor : "#000000",
        googleIconColor : "#0F9D58",
    },
    dark : {
        black : "#000000",
        white : "#FFFFFF",
        red : "#EF4444",
        blue : "#1877F2",
        orange : "#F97316",
        yellow : "#FFE000",
        transparent : "rgba(0,0,0,0.7)",
        primaryColor: '#1B1C1D',
        bgColor : '#131314',
        tavIndicatorColor : "#1877F2",
        tabActiveColor : "#2774FF",
        tavInActiveColor : "#A1A4AA",
        imgBgColor : "#2C2D2E",
        editTxtPrimaryCont : "#2C2D2E",
        editTxtSecondaryCont : "#323334",
        editTxtColor : '#DDE0E6',
        commonBtnColor : '#1877F2',
        primaryTxtColor : '#DDE0E5',
        secondaryTxtColor : '#A1A4AA',
        cardTitleTxtColor : '#000000',
        cardDesTxtColor : '#707070',
        bottomNavActiveColor : '#1780FF',
        bottomNavInActiveColor : '#DCE0E5',
        skeletonContentColor : '#A3A3A3',
        cardBgColor : '#1B1C1D',
        cardPrimaryColor : '#2C2D2E',
        iconBgColor : "#323334",
        primaryIconColor : '#DDE0E5',
        secondaryIconColor : "#323334",
        viewLineColor : "#2C2D2E",
        fbIconColor : "#4267B2",
        appleIconColor : "#000000",
        googleIconColor : "#0F9D58",
    },
}
